//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Data.Objects.DataClasses.EdmSchemaAttribute()]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("SPPrimitives.SettingsProviders.DatabaseModel", "Section_ApplcationSettings_FK", "Section", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(SPPrimitives.SettingsProvider.Section), "ApplcationSetting", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SPPrimitives.SettingsProvider.ApplcationSetting))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("SPPrimitives.SettingsProviders.DatabaseModel", "SqlConnection_SqlConnectionNames_FK", "SqlConnectionString", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(SPPrimitives.SettingsProvider.SqlConnectionString), "SqlConnectionName", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SPPrimitives.SettingsProvider.SqlConnectionName))]

// Original file name:
// Generation date: 9/24/2010 9:59:31 PM
namespace SPPrimitives.SettingsProvider
{
    
    /// <summary>
    /// There are no comments for Database in the schema.
    /// </summary>
    public partial class Database : global::System.Data.Objects.ObjectContext
    {
        /// <summary>
        /// Initializes a new Database object using the connection string found in the 'Database' section of the application configuration file.
        /// </summary>
        public Database() : 
                base("name=Database", "Database")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new Database object.
        /// </summary>
        public Database(string connectionString) : 
                base(connectionString, "Database")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new Database object.
        /// </summary>
        public Database(global::System.Data.EntityClient.EntityConnection connection) : 
                base(connection, "Database")
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// There are no comments for ApplcationSettings in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Data.Objects.ObjectQuery<ApplcationSetting> ApplcationSettings
        {
            get
            {
                if ((this._ApplcationSettings == null))
                {
                    this._ApplcationSettings = base.CreateQuery<ApplcationSetting>("[ApplcationSettings]");
                }
                return this._ApplcationSettings;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Data.Objects.ObjectQuery<ApplcationSetting> _ApplcationSettings;
        /// <summary>
        /// There are no comments for Sections in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Data.Objects.ObjectQuery<Section> Sections
        {
            get
            {
                if ((this._Sections == null))
                {
                    this._Sections = base.CreateQuery<Section>("[Sections]");
                }
                return this._Sections;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Data.Objects.ObjectQuery<Section> _Sections;
        /// <summary>
        /// There are no comments for SqlConnectionNames in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Data.Objects.ObjectQuery<SqlConnectionName> SqlConnectionNames
        {
            get
            {
                if ((this._SqlConnectionNames == null))
                {
                    this._SqlConnectionNames = base.CreateQuery<SqlConnectionName>("[SqlConnectionNames]");
                }
                return this._SqlConnectionNames;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Data.Objects.ObjectQuery<SqlConnectionName> _SqlConnectionNames;
        /// <summary>
        /// There are no comments for SqlConnectionStrings in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Data.Objects.ObjectQuery<SqlConnectionString> SqlConnectionStrings
        {
            get
            {
                if ((this._SqlConnectionStrings == null))
                {
                    this._SqlConnectionStrings = base.CreateQuery<SqlConnectionString>("[SqlConnectionStrings]");
                }
                return this._SqlConnectionStrings;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Data.Objects.ObjectQuery<SqlConnectionString> _SqlConnectionStrings;
        /// <summary>
        /// There are no comments for ApplcationSettings in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public void AddToApplcationSettings(ApplcationSetting applcationSetting)
        {
            base.AddObject("ApplcationSettings", applcationSetting);
        }
        /// <summary>
        /// There are no comments for Sections in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public void AddToSections(Section section)
        {
            base.AddObject("Sections", section);
        }
        /// <summary>
        /// There are no comments for SqlConnectionNames in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public void AddToSqlConnectionNames(SqlConnectionName sqlConnectionName)
        {
            base.AddObject("SqlConnectionNames", sqlConnectionName);
        }
        /// <summary>
        /// There are no comments for SqlConnectionStrings in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public void AddToSqlConnectionStrings(SqlConnectionString sqlConnectionString)
        {
            base.AddObject("SqlConnectionStrings", sqlConnectionString);
        }
    }
    /// <summary>
    /// There are no comments for SPPrimitives.SettingsProviders.DatabaseModel.ApplcationSetting in the schema.
    /// </summary>
    /// <KeyProperties>
    /// SectionId
    /// Name
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="SPPrimitives.SettingsProviders.DatabaseModel", Name="ApplcationSetting")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class ApplcationSetting : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new ApplcationSetting object.
        /// </summary>
        /// <param name="sectionId">Initial value of SectionId.</param>
        /// <param name="name">Initial value of Name.</param>
        /// <param name="serializeAs">Initial value of SerializeAs.</param>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public static ApplcationSetting CreateApplcationSetting(int sectionId, string name, int serializeAs)
        {
            ApplcationSetting applcationSetting = new ApplcationSetting();
            applcationSetting.SectionId = sectionId;
            applcationSetting.Name = name;
            applcationSetting.SerializeAs = serializeAs;
            return applcationSetting;
        }
        /// <summary>
        /// There are no comments for property SectionId in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public int SectionId
        {
            get
            {
                return this._SectionId;
            }
            set
            {
                this.OnSectionIdChanging(value);
                this.ReportPropertyChanging("SectionId");
                this._SectionId = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("SectionId");
                this.OnSectionIdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private int _SectionId;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnSectionIdChanging(int value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnSectionIdChanged();
        /// <summary>
        /// There are no comments for property Name in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this.ReportPropertyChanging("Name");
                this._Name = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Name");
                this.OnNameChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _Name;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNameChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for property SerializeAs in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public int SerializeAs
        {
            get
            {
                return this._SerializeAs;
            }
            set
            {
                this.OnSerializeAsChanging(value);
                this.ReportPropertyChanging("SerializeAs");
                this._SerializeAs = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("SerializeAs");
                this.OnSerializeAsChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private int _SerializeAs;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnSerializeAsChanging(int value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnSerializeAsChanged();
        /// <summary>
        /// There are no comments for property Value in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string Value
        {
            get
            {
                return this._Value;
            }
            set
            {
                this.OnValueChanging(value);
                this.ReportPropertyChanging("Value");
                this._Value = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Value");
                this.OnValueChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _Value;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnValueChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnValueChanged();
        /// <summary>
        /// There are no comments for Section in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("SPPrimitives.SettingsProviders.DatabaseModel", "Section_ApplcationSettings_FK", "Section")]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public Section Section
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Section>("SPPrimitives.SettingsProviders.DatabaseModel.Section_ApplcationSettings_FK", "Section").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Section>("SPPrimitives.SettingsProviders.DatabaseModel.Section_ApplcationSettings_FK", "Section").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for Section in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<Section> SectionReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Section>("SPPrimitives.SettingsProviders.DatabaseModel.Section_ApplcationSettings_FK", "Section");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Section>("SPPrimitives.SettingsProviders.DatabaseModel.Section_ApplcationSettings_FK", "Section", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for SPPrimitives.SettingsProviders.DatabaseModel.Section in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="SPPrimitives.SettingsProviders.DatabaseModel", Name="Section")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Section : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Section object.
        /// </summary>
        /// <param name="id">Initial value of Id.</param>
        /// <param name="name">Initial value of Name.</param>
        /// <param name="assemblyName">Initial value of AssemblyName.</param>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public static Section CreateSection(int id, string name, string assemblyName)
        {
            Section section = new Section();
            section.Id = id;
            section.Name = name;
            section.AssemblyName = assemblyName;
            return section;
        }
        /// <summary>
        /// There are no comments for property Id in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this.ReportPropertyChanging("Id");
                this._Id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Id");
                this.OnIdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private int _Id;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnIdChanging(int value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for property Name in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this.ReportPropertyChanging("Name");
                this._Name = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Name");
                this.OnNameChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _Name;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNameChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for property AssemblyName in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string AssemblyName
        {
            get
            {
                return this._AssemblyName;
            }
            set
            {
                this.OnAssemblyNameChanging(value);
                this.ReportPropertyChanging("AssemblyName");
                this._AssemblyName = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("AssemblyName");
                this.OnAssemblyNameChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _AssemblyName;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnAssemblyNameChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnAssemblyNameChanged();
        /// <summary>
        /// There are no comments for ApplcationSettings in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("SPPrimitives.SettingsProviders.DatabaseModel", "Section_ApplcationSettings_FK", "ApplcationSetting")]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<ApplcationSetting> ApplcationSettings
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<ApplcationSetting>("SPPrimitives.SettingsProviders.DatabaseModel.Section_ApplcationSettings_FK", "ApplcationSetting");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<ApplcationSetting>("SPPrimitives.SettingsProviders.DatabaseModel.Section_ApplcationSettings_FK", "ApplcationSetting", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for SPPrimitives.SettingsProviders.DatabaseModel.SqlConnectionName in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Name
    /// SqlConnectionId
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="SPPrimitives.SettingsProviders.DatabaseModel", Name="SqlConnectionName")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class SqlConnectionName : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new SqlConnectionName object.
        /// </summary>
        /// <param name="name">Initial value of Name.</param>
        /// <param name="sqlConnectionId">Initial value of SqlConnectionId.</param>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public static SqlConnectionName CreateSqlConnectionName(string name, int sqlConnectionId)
        {
            SqlConnectionName sqlConnectionName = new SqlConnectionName();
            sqlConnectionName.Name = name;
            sqlConnectionName.SqlConnectionId = sqlConnectionId;
            return sqlConnectionName;
        }
        /// <summary>
        /// There are no comments for property Name in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this.ReportPropertyChanging("Name");
                this._Name = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Name");
                this.OnNameChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _Name;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNameChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for property SqlConnectionId in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public int SqlConnectionId
        {
            get
            {
                return this._SqlConnectionId;
            }
            set
            {
                this.OnSqlConnectionIdChanging(value);
                this.ReportPropertyChanging("SqlConnectionId");
                this._SqlConnectionId = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("SqlConnectionId");
                this.OnSqlConnectionIdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private int _SqlConnectionId;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnSqlConnectionIdChanging(int value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnSqlConnectionIdChanged();
        /// <summary>
        /// There are no comments for SqlConnectionString in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("SPPrimitives.SettingsProviders.DatabaseModel", "SqlConnection_SqlConnectionNames_FK", "SqlConnectionString")]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public SqlConnectionString SqlConnectionString
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<SqlConnectionString>("SPPrimitives.SettingsProviders.DatabaseModel.SqlConnection_SqlConnectionNames_FK", "SqlConnectionString").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<SqlConnectionString>("SPPrimitives.SettingsProviders.DatabaseModel.SqlConnection_SqlConnectionNames_FK", "SqlConnectionString").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for SqlConnectionString in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<SqlConnectionString> SqlConnectionStringReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<SqlConnectionString>("SPPrimitives.SettingsProviders.DatabaseModel.SqlConnection_SqlConnectionNames_FK", "SqlConnectionString");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<SqlConnectionString>("SPPrimitives.SettingsProviders.DatabaseModel.SqlConnection_SqlConnectionNames_FK", "SqlConnectionString", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for SPPrimitives.SettingsProviders.DatabaseModel.SqlConnectionString in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="SPPrimitives.SettingsProviders.DatabaseModel", Name="SqlConnectionString")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class SqlConnectionString : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new SqlConnectionString object.
        /// </summary>
        /// <param name="id">Initial value of Id.</param>
        /// <param name="catalog">Initial value of Catalog.</param>
        /// <param name="connectionString">Initial value of ConnectionString.</param>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public static SqlConnectionString CreateSqlConnectionString(int id, string catalog, string connectionString)
        {
            SqlConnectionString sqlConnectionString = new SqlConnectionString();
            sqlConnectionString.Id = id;
            sqlConnectionString.Catalog = catalog;
            sqlConnectionString.ConnectionString = connectionString;
            return sqlConnectionString;
        }
        /// <summary>
        /// There are no comments for property Id in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this.ReportPropertyChanging("Id");
                this._Id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Id");
                this.OnIdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private int _Id;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnIdChanging(int value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for property Catalog in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string Catalog
        {
            get
            {
                return this._Catalog;
            }
            set
            {
                this.OnCatalogChanging(value);
                this.ReportPropertyChanging("Catalog");
                this._Catalog = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Catalog");
                this.OnCatalogChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _Catalog;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnCatalogChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnCatalogChanged();
        /// <summary>
        /// There are no comments for property ConnectionString in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string ConnectionString
        {
            get
            {
                return this._ConnectionString;
            }
            set
            {
                this.OnConnectionStringChanging(value);
                this.ReportPropertyChanging("ConnectionString");
                this._ConnectionString = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("ConnectionString");
                this.OnConnectionStringChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _ConnectionString;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnConnectionStringChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnConnectionStringChanged();
        /// <summary>
        /// There are no comments for SqlConnectionNames in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("SPPrimitives.SettingsProviders.DatabaseModel", "SqlConnection_SqlConnectionNames_FK", "SqlConnectionName")]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<SqlConnectionName> SqlConnectionNames
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<SqlConnectionName>("SPPrimitives.SettingsProviders.DatabaseModel.SqlConnection_SqlConnectionNames_FK", "SqlConnectionName");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<SqlConnectionName>("SPPrimitives.SettingsProviders.DatabaseModel.SqlConnection_SqlConnectionNames_FK", "SqlConnectionName", value);
                }
            }
        }
    }
}
