//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Data.Objects.DataClasses.EdmSchemaAttribute()]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("SPPrimitives.SettingsProvider.Database", "FK_SqlConnectionNames_Sections", "Sections", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(SharePointPrimitives.SettingsProvider.Section), "SqlConnectionNames", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SharePointPrimitives.SettingsProvider.SqlConnectionName))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("SPPrimitives.SettingsProvider.Database", "FK_SqlConnectionNames_SqlConnectionStrings", "SqlConnectionStrings", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(SharePointPrimitives.SettingsProvider.SqlConnectionString), "SqlConnectionNames", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SharePointPrimitives.SettingsProvider.SqlConnectionName))]
[assembly: global::System.Data.Objects.DataClasses.EdmRelationshipAttribute("SPPrimitives.SettingsProvider.Database", "FK_ApplcationSettings_Sections1", "Section", global::System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(SharePointPrimitives.SettingsProvider.Section), "ApplicationSetting", global::System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SharePointPrimitives.SettingsProvider.ApplicationSetting))]

// Original file name:
// Generation date: 10/31/2010 3:52:30 PM
namespace SharePointPrimitives.SettingsProvider
{
    
    /// <summary>
    /// There are no comments for SettingsProviderDatabase in the schema.
    /// </summary>
    public partial class SettingsProviderDatabase : global::System.Data.Objects.ObjectContext
    {
        /// <summary>
        /// Initializes a new SettingsProviderDatabase object using the connection string found in the 'SettingsProviderDatabase' section of the application configuration file.
        /// </summary>
        public SettingsProviderDatabase() : 
                base("name=SettingsProviderDatabase", "SettingsProviderDatabase")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new SettingsProviderDatabase object.
        /// </summary>
        public SettingsProviderDatabase(string connectionString) : 
                base(connectionString, "SettingsProviderDatabase")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new SettingsProviderDatabase object.
        /// </summary>
        public SettingsProviderDatabase(global::System.Data.EntityClient.EntityConnection connection) : 
                base(connection, "SettingsProviderDatabase")
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// There are no comments for Sections in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Data.Objects.ObjectQuery<Section> Sections
        {
            get
            {
                if ((this._Sections == null))
                {
                    this._Sections = base.CreateQuery<Section>("[Sections]");
                }
                return this._Sections;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Data.Objects.ObjectQuery<Section> _Sections;
        /// <summary>
        /// There are no comments for SqlConnectionNames in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Data.Objects.ObjectQuery<SqlConnectionName> SqlConnectionNames
        {
            get
            {
                if ((this._SqlConnectionNames == null))
                {
                    this._SqlConnectionNames = base.CreateQuery<SqlConnectionName>("[SqlConnectionNames]");
                }
                return this._SqlConnectionNames;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Data.Objects.ObjectQuery<SqlConnectionName> _SqlConnectionNames;
        /// <summary>
        /// There are no comments for SqlConnectionStrings in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Data.Objects.ObjectQuery<SqlConnectionString> SqlConnectionStrings
        {
            get
            {
                if ((this._SqlConnectionStrings == null))
                {
                    this._SqlConnectionStrings = base.CreateQuery<SqlConnectionString>("[SqlConnectionStrings]");
                }
                return this._SqlConnectionStrings;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Data.Objects.ObjectQuery<SqlConnectionString> _SqlConnectionStrings;
        /// <summary>
        /// There are no comments for ApplicationSettings in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Data.Objects.ObjectQuery<ApplicationSetting> ApplicationSettings
        {
            get
            {
                if ((this._ApplicationSettings == null))
                {
                    this._ApplicationSettings = base.CreateQuery<ApplicationSetting>("[ApplicationSettings]");
                }
                return this._ApplicationSettings;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Data.Objects.ObjectQuery<ApplicationSetting> _ApplicationSettings;
        /// <summary>
        /// There are no comments for Sections in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public void AddToSections(Section section)
        {
            base.AddObject("Sections", section);
        }
        /// <summary>
        /// There are no comments for SqlConnectionNames in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public void AddToSqlConnectionNames(SqlConnectionName sqlConnectionName)
        {
            base.AddObject("SqlConnectionNames", sqlConnectionName);
        }
        /// <summary>
        /// There are no comments for SqlConnectionStrings in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public void AddToSqlConnectionStrings(SqlConnectionString sqlConnectionString)
        {
            base.AddObject("SqlConnectionStrings", sqlConnectionString);
        }
        /// <summary>
        /// There are no comments for ApplicationSettings in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public void AddToApplicationSettings(ApplicationSetting applicationSetting)
        {
            base.AddObject("ApplicationSettings", applicationSetting);
        }
    }
    /// <summary>
    /// There are no comments for SPPrimitives.SettingsProvider.Database.Section in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="SPPrimitives.SettingsProvider.Database", Name="Section")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class Section : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new Section object.
        /// </summary>
        /// <param name="id">Initial value of Id.</param>
        /// <param name="name">Initial value of Name.</param>
        /// <param name="assemblyName">Initial value of AssemblyName.</param>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public static Section CreateSection(int id, string name, string assemblyName)
        {
            Section section = new Section();
            section.Id = id;
            section.Name = name;
            section.AssemblyName = assemblyName;
            return section;
        }
        /// <summary>
        /// There are no comments for property Id in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this.ReportPropertyChanging("Id");
                this._Id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Id");
                this.OnIdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private int _Id;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnIdChanging(int value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for property Name in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this.ReportPropertyChanging("Name");
                this._Name = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Name");
                this.OnNameChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _Name;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNameChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for property AssemblyName in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string AssemblyName
        {
            get
            {
                return this._AssemblyName;
            }
            set
            {
                this.OnAssemblyNameChanging(value);
                this.ReportPropertyChanging("AssemblyName");
                this._AssemblyName = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("AssemblyName");
                this.OnAssemblyNameChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _AssemblyName;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnAssemblyNameChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnAssemblyNameChanged();
        /// <summary>
        /// There are no comments for SqlConnectionNames in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("SPPrimitives.SettingsProvider.Database", "FK_SqlConnectionNames_Sections", "SqlConnectionNames")]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<SqlConnectionName> SqlConnectionNames
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<SqlConnectionName>("SPPrimitives.SettingsProvider.Database.FK_SqlConnectionNames_Sections", "SqlConnectionNames");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<SqlConnectionName>("SPPrimitives.SettingsProvider.Database.FK_SqlConnectionNames_Sections", "SqlConnectionNames", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for ApplicationSettings in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("SPPrimitives.SettingsProvider.Database", "FK_ApplcationSettings_Sections1", "ApplicationSetting")]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<ApplicationSetting> ApplicationSettings
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<ApplicationSetting>("SPPrimitives.SettingsProvider.Database.FK_ApplcationSettings_Sections1", "ApplicationSetting");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<ApplicationSetting>("SPPrimitives.SettingsProvider.Database.FK_ApplcationSettings_Sections1", "ApplicationSetting", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for SPPrimitives.SettingsProvider.Database.SqlConnectionName in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Name
    /// SqlConnectionId
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="SPPrimitives.SettingsProvider.Database", Name="SqlConnectionName")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class SqlConnectionName : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new SqlConnectionName object.
        /// </summary>
        /// <param name="name">Initial value of Name.</param>
        /// <param name="sqlConnectionId">Initial value of SqlConnectionId.</param>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public static SqlConnectionName CreateSqlConnectionName(string name, int sqlConnectionId)
        {
            SqlConnectionName sqlConnectionName = new SqlConnectionName();
            sqlConnectionName.Name = name;
            sqlConnectionName.SqlConnectionId = sqlConnectionId;
            return sqlConnectionName;
        }
        /// <summary>
        /// There are no comments for property Name in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this.ReportPropertyChanging("Name");
                this._Name = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Name");
                this.OnNameChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _Name;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNameChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for property SqlConnectionId in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public int SqlConnectionId
        {
            get
            {
                return this._SqlConnectionId;
            }
            set
            {
                this.OnSqlConnectionIdChanging(value);
                this.ReportPropertyChanging("SqlConnectionId");
                this._SqlConnectionId = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("SqlConnectionId");
                this.OnSqlConnectionIdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private int _SqlConnectionId;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnSqlConnectionIdChanging(int value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnSqlConnectionIdChanged();
        /// <summary>
        /// There are no comments for Section in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("SPPrimitives.SettingsProvider.Database", "FK_SqlConnectionNames_Sections", "Sections")]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public Section Section
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Section>("SPPrimitives.SettingsProvider.Database.FK_SqlConnectionNames_Sections", "Sections").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Section>("SPPrimitives.SettingsProvider.Database.FK_SqlConnectionNames_Sections", "Sections").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for Section in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<Section> SectionReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Section>("SPPrimitives.SettingsProvider.Database.FK_SqlConnectionNames_Sections", "Sections");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Section>("SPPrimitives.SettingsProvider.Database.FK_SqlConnectionNames_Sections", "Sections", value);
                }
            }
        }
        /// <summary>
        /// There are no comments for SqlConnectionString in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("SPPrimitives.SettingsProvider.Database", "FK_SqlConnectionNames_SqlConnectionStrings", "SqlConnectionStrings")]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public SqlConnectionString SqlConnectionString
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<SqlConnectionString>("SPPrimitives.SettingsProvider.Database.FK_SqlConnectionNames_SqlConnectionStrings" +
                        "", "SqlConnectionStrings").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<SqlConnectionString>("SPPrimitives.SettingsProvider.Database.FK_SqlConnectionNames_SqlConnectionStrings" +
                        "", "SqlConnectionStrings").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for SqlConnectionString in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<SqlConnectionString> SqlConnectionStringReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<SqlConnectionString>("SPPrimitives.SettingsProvider.Database.FK_SqlConnectionNames_SqlConnectionStrings" +
                        "", "SqlConnectionStrings");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<SqlConnectionString>("SPPrimitives.SettingsProvider.Database.FK_SqlConnectionNames_SqlConnectionStrings" +
                            "", "SqlConnectionStrings", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for SPPrimitives.SettingsProvider.Database.SqlConnectionString in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="SPPrimitives.SettingsProvider.Database", Name="SqlConnectionString")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class SqlConnectionString : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new SqlConnectionString object.
        /// </summary>
        /// <param name="id">Initial value of Id.</param>
        /// <param name="connectionString">Initial value of ConnectionString.</param>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public static SqlConnectionString CreateSqlConnectionString(int id, string connectionString)
        {
            SqlConnectionString sqlConnectionString = new SqlConnectionString();
            sqlConnectionString.Id = id;
            sqlConnectionString.ConnectionString = connectionString;
            return sqlConnectionString;
        }
        /// <summary>
        /// There are no comments for property Id in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this.ReportPropertyChanging("Id");
                this._Id = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("Id");
                this.OnIdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private int _Id;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnIdChanging(int value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for property ConnectionString in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string ConnectionString
        {
            get
            {
                return this._ConnectionString;
            }
            set
            {
                this.OnConnectionStringChanging(value);
                this.ReportPropertyChanging("ConnectionString");
                this._ConnectionString = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("ConnectionString");
                this.OnConnectionStringChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _ConnectionString;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnConnectionStringChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnConnectionStringChanged();
        /// <summary>
        /// There are no comments for SqlConnectionNames in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("SPPrimitives.SettingsProvider.Database", "FK_SqlConnectionNames_SqlConnectionStrings", "SqlConnectionNames")]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityCollection<SqlConnectionName> SqlConnectionNames
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedCollection<SqlConnectionName>("SPPrimitives.SettingsProvider.Database.FK_SqlConnectionNames_SqlConnectionStrings" +
                        "", "SqlConnectionNames");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedCollection<SqlConnectionName>("SPPrimitives.SettingsProvider.Database.FK_SqlConnectionNames_SqlConnectionStrings" +
                            "", "SqlConnectionNames", value);
                }
            }
        }
    }
    /// <summary>
    /// There are no comments for SPPrimitives.SettingsProvider.Database.ApplicationSetting in the schema.
    /// </summary>
    /// <KeyProperties>
    /// SectionId
    /// Name
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="SPPrimitives.SettingsProvider.Database", Name="ApplicationSetting")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class ApplicationSetting : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new ApplicationSetting object.
        /// </summary>
        /// <param name="sectionId">Initial value of SectionId.</param>
        /// <param name="name">Initial value of Name.</param>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public static ApplicationSetting CreateApplicationSetting(int sectionId, string name)
        {
            ApplicationSetting applicationSetting = new ApplicationSetting();
            applicationSetting.SectionId = sectionId;
            applicationSetting.Name = name;
            return applicationSetting;
        }
        /// <summary>
        /// There are no comments for property SectionId in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public int SectionId
        {
            get
            {
                return this._SectionId;
            }
            set
            {
                this.OnSectionIdChanging(value);
                this.ReportPropertyChanging("SectionId");
                this._SectionId = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("SectionId");
                this.OnSectionIdChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private int _SectionId;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnSectionIdChanging(int value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnSectionIdChanged();
        /// <summary>
        /// There are no comments for property Name in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this.ReportPropertyChanging("Name");
                this._Name = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("Name");
                this.OnNameChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _Name;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNameChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for property Value in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string Value
        {
            get
            {
                return this._Value;
            }
            set
            {
                this.OnValueChanging(value);
                this.ReportPropertyChanging("Value");
                this._Value = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Value");
                this.OnValueChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _Value;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnValueChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnValueChanged();
        /// <summary>
        /// There are no comments for property Type in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string Type
        {
            get
            {
                return this._Type;
            }
            set
            {
                this.OnTypeChanging(value);
                this.ReportPropertyChanging("Type");
                this._Type = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, true);
                this.ReportPropertyChanged("Type");
                this.OnTypeChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _Type;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnTypeChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void OnTypeChanged();
        /// <summary>
        /// There are no comments for Section in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("SPPrimitives.SettingsProvider.Database", "FK_ApplcationSettings_Sections1", "Section")]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Xml.Serialization.XmlIgnoreAttribute()]
        [global::System.Xml.Serialization.SoapIgnoreAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public Section Section
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Section>("SPPrimitives.SettingsProvider.Database.FK_ApplcationSettings_Sections1", "Section").Value;
            }
            set
            {
                ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Section>("SPPrimitives.SettingsProvider.Database.FK_ApplcationSettings_Sections1", "Section").Value = value;
            }
        }
        /// <summary>
        /// There are no comments for Section in the schema.
        /// </summary>
        [global::System.ComponentModel.BrowsableAttribute(false)]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        public global::System.Data.Objects.DataClasses.EntityReference<Section> SectionReference
        {
            get
            {
                return ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.GetRelatedReference<Section>("SPPrimitives.SettingsProvider.Database.FK_ApplcationSettings_Sections1", "Section");
            }
            set
            {
                if ((value != null))
                {
                    ((global::System.Data.Objects.DataClasses.IEntityWithRelationships)(this)).RelationshipManager.InitializeRelatedReference<Section>("SPPrimitives.SettingsProvider.Database.FK_ApplcationSettings_Sections1", "Section", value);
                }
            }
        }
    }
}
