ALTER TABLE [dbo].[SqlConnectionNames]
    ADD CONSTRAINT [PK_SqlConnectionNames] PRIMARY KEY CLUSTERED ([SqlConnectionId] ASC, [SectionId] ASC) WITH (ALLOW_PAGE_LOCKS = ON, ALLOW_ROW_LOCKS = ON, PAD_INDEX = OFF, IGNORE_DUP_KEY = OFF, STATISTICS_NORECOMPUTE = OFF);

